### ISSUE TITLE
No window pops up

### ISSUE THREAD

**Issue by YopYopBV** [eddhuh/Better-Pokecord#2]
I downloaded the latest release and then clicked on the .exe file. Task manager tells me the program is running (albeit only in the background) but no window pops up.

![eth](https://user-images.githubusercontent.com/47813705/53082600-1d9d7100-34f5-11e9-9847-fc8ec8a5c6fa.PNG)

![trh4wwht](https://user-images.githubusercontent.com/47813705/53082784-84228f00-34f5-11e9-8df9-243794eb592e.PNG)

**Comment by eddhuh** [comment]
It's not meant to display any windows when it finishes starting up. The windows/macros should only be working if Discord is the active window, or the active window has the word "Discord" somewhere in its title.

If you're sure everything is being done correctly and I've misunderstood, try to run as admin.

I'm going to go ahead and close this issue. I think this is just a miscommunication, and the script seems to have started up with no errors based on your screenshots.
